import { motion } from 'motion/react'
import { ArrowUpRight, Sparkles, Target, Zap } from 'lucide-react'

const pillars = [
  {
    icon: Target,
    title: 'Real implementation',
    body: 'No theory dumps. Every module maps to an action you run the same day on a real campaign.',
  },
  {
    icon: Zap,
    title: 'Organic traffic focus',
    body: 'Built for zero ad spend. USA traffic method and content-locking flows that scale without a media budget.',
  },
  {
    icon: Sparkles,
    title: 'Mentorship window',
    body: 'Three months of structured support so questions get answered while you execute — not after the momentum dies.',
  },
]

export default function WhyChooseSection() {
  return (
    <motion.section
      initial={{ opacity: 0, y: 40 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.15, margin: '0px 0px -10% 0px' }}
      transition={{ duration: 0.85, ease: [0.22, 1, 0.36, 1] }}
      className="mt-16 will-change-transform-opacity sm:mt-20"
    >
      <div className="glass-panel relative overflow-hidden rounded-[32px] p-6 sm:p-10">
        <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-cyan-400/60 to-transparent" />
        <div className="grid gap-8 lg:grid-cols-[1.1fr_1fr] lg:items-center">
          <div>
            <span className="chip">
              <Sparkles size={12} className="text-cyan-500" />
              <span>Why choose us</span>
            </span>
            <h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-950 dark:text-white sm:text-4xl">
              Practical CPA strategies,{' '}
              <span className="text-gradient-brand">built for real markets.</span>
            </h2>
            <p className="mt-4 max-w-xl text-sm leading-7 text-slate-600 dark:text-slate-300 sm:text-[15px]">
              We focus on practical CPA strategies and real implementation,
              helping students build systems that work in real markets — not
              polished theory that breaks the first time it meets a live offer.
            </p>

            <div className="mt-6 grid gap-3">
              {pillars.map(({ icon: Icon, title, body }, idx) => (
                <motion.div
                  key={title}
                  initial={{ opacity: 0, y: 18 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, amount: 0.3 }}
                  transition={{
                    delay: 0.08 * idx,
                    duration: 0.6,
                    ease: [0.22, 1, 0.36, 1],
                  }}
                  whileHover={{ y: -2 }}
                  className="flex items-start gap-3 rounded-2xl border border-white/10 bg-white/50 p-4 transition-shadow hover:shadow-[0_16px_40px_-20px_rgba(15,23,42,0.25)] dark:bg-white/5"
                >
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-950 text-white dark:bg-white dark:text-slate-950">
                    <Icon size={18} />
                  </div>
                  <div>
                    <div className="text-sm font-semibold text-slate-900 dark:text-white">
                      {title}
                    </div>
                    <p className="mt-1 text-[13px] leading-6 text-slate-600 dark:text-slate-400">
                      {body}
                    </p>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>

          <motion.div
            initial={{ opacity: 0, y: 18 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
            className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-indigo-600 via-blue-600 to-cyan-500 p-7 text-white shadow-[0_40px_100px_-30px_rgba(37,99,235,0.65)]"
          >
            <div className="absolute -right-16 -top-16 h-52 w-52 rounded-full bg-white/10 blur-3xl" />
            <div className="absolute -bottom-20 -left-10 h-48 w-48 rounded-full bg-cyan-200/20 blur-3xl" />
            <div className="relative">
              <div className="text-[11px] font-semibold uppercase tracking-[0.28em] text-white/75">
                Community-wide
              </div>
              <div className="mt-4 text-5xl font-bold tracking-tight sm:text-6xl">
                $15,000+
              </div>
              <p className="mt-3 text-sm leading-6 text-white/85 sm:text-[15px]">
                Generated by students using the same CPA strategies taught
                inside CPA MASTERY — verified through public earning screenshots.
              </p>
              <a
                href="https://t.me/MkArmy01"
                target="_blank"
                rel="noreferrer"
                className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-semibold text-slate-950 transition-transform duration-300 hover:-translate-y-0.5"
              >
                Check proof inside our Telegram
                <ArrowUpRight size={16} />
              </a>
            </div>
          </motion.div>
        </div>
      </div>
    </motion.section>
  )
}
